###GET(Read all users)
get http://localhost:3000/user-api/users

###GET(Read a user by id)
get http://localhost:3000/user-api/users/vamsi

###POST(create new User)
post http://localhost:3000/user-api/user
Content-Type: application/json

{
    
    "name":"prasanth",
    "age":25

}


###PUT(Update a User)
put http://localhost:3000/user-api/user
Content-Type: application/json

{
   
    "name": "vamsi",
    "age": 50,
    "salary": 80000,
    "city": "bangalore"
}
   


###DELETE(Delete user by id)
delete http://localhost:3000/user-api/users/prasanth



###PRODUCT API REQ
get http://localhost:3000/product-api/products